### ISSUE TITLE
Deletion of usecase concrete

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#105]
We started to move everything into the minimum working example and the demonstrator as well as the paper, is there anyone against trying to delete the concrete usecase?

**Comment by eriktamsen** [comment]
Good plan. I don't think there should be something relevant in there anymore.
I will make a branch for this issue, delete the folder and see if the CI still works.
Then we can still wait a week to give people time to respond to this, before we merge. Nothing will be lost anyways due to Git, only more annoying to recover :D.
@soudehMasoudian, @mattheokru, @AidaZt, @atulag0711, @alFrie, please comment, if there is still something in the concrete usecase that needs to be moved, before it is deleted.

**Comment by eriktamsen** [comment]
Deleting the folder does not break the CI, as expected.
I moved the "three_point_bending_example", which was once implemented to be a simple predictive simulation to the correct location. Once the PR #57 from @atulag0711 is merged, we can include this in the minimum working example.
If anyone else needs some files "saved", please let me know which file and where it need to go (or just do it yourself :D). 
I will merge the branch at the end of the month unless there are objections.
