### ISSUE TITLE
Correlation in model_error

### ISSUE THREAD

**Issue by ajafarihub** [BAMresearch/LebeDigital#2]
The issue is how to deal with any kind of **correlation** existing in either/both of:
- data
- (forward) model output
, which naturally appears in the computed model_error, as well.

Theoretically, such correlation(s) are represented by means of some _**correlation matrices**_ (denoted by **Cov**), which can _contribute_ to the calibration algorithm at some point. The goal is to figure out a structured general way of considering this _contribution_, particularly concerning the computation of the model error.

**Comment by ajafarihub** [comment]
As I created the issue, I put some of my thoughts about it, as well.

1- IMO, this is something totally related to the optimization algorithm, i.e. an algorithm might be essentially incapable of considering any correlated data/model output. So, we might need to see this requirement just as an _option_ in the library.

2- Those algorithms which are able to deal with correlated data/model output most likely require to either be provided by the correlation matrices or to identify them.

2-1- If we need to provide the correlation matrices for the optimizer, I think this should be a duty of the user of the library; i.e. to give these matrices to some class of the library at some point. Now, two questions come to my mind:
2-1-1 To which class of the library should these quantities be given? IMO, the model_error (or combined error) class.
2-1-2- Which methods/classes can we consider/develop for compting these correlations; e.g. according to a space-domain, time, etc. .

2-2- If the optimization algorighm should identify these correlation matrices, I see no issue, since this is simply something which is considered within the implementation of the optimizer class. Isn't is so?

**Comment by joergfunger** [comment]
You are right that using this information depends on the optimizer to be used. However, if we want to use this, there should be a general interface. From my point of view, we need a SpaceTime model error class that has a well defined structure and is used as a base class for all model errors that want to use this feature. This class can then provide different kernel functions to compute the covariance matrix. As a precondition, we would need to be able to extract for each entry in this model error class the corresponding time and spatial position. The question is, how this interface should look like.

**Comment by ajafarihub** [comment]
I see that you would like to shift the computation of covariance matrices into the model_error class. I think nevertheless, this can make things a bit complicated, because we would need much information from the model/data in order to compute the covariance matrices (let's denote them by **Cov**). An important point IMO is: **Cov** is either experiment-dependent or model-dependent. So, why to shift its computation into the model_error class, which is NOT a direct responsible for either of data/model ? Thus, I would say, another approach is more natural: to shift the computation of **Cov** into somewhere outside of the model_error and only give the computed **Cov** as an input to the model_error. Briefly speaking, I see model_error class nothing more than just a simple subtraction: model_output - data. In the present context however, either of data/model_output should already consider any possible correlation stuff within their own classes and just before they appear to be subtracted from each other. This approach is what I would find easier to interpret and generalize.

**Comment by joergfunger** [comment]
So there are two things. First, the model error is not always a pure subtraction, but (as in your case) you might provide the data to the forward model and compute e.g. the residual of your balance equations. Second, you can put it in separate classes or functions, but we need to have a class that allows us to define correlations between model errors in space and time. Thus, we would have to now for each individual model error entry (in this large vector), what is the corresponding time/space. If the number of sensors over time does not change, then this could be easier represented by some tensor product type storage scheme, e.g. first storing all values at t=t_0, then t=t_1 and so forth. You would then only need one vector with the spatial coordinates and one with the times and based on that you can define the CoV. What do you mean be CoC is either experiment or model dependent? And what would be in your opinion the structure of a class for the computation of these CoV?

**Comment by ajafarihub** [comment]
I came up with the idea of developing appropriate classes for typical experiments/processes which we deal with. The objectives of such classes are:
- to gather all relevant information collected from any particular experiment
- (regarding the present context) to possibly compute **Cov** matrix depending on space or time or the combination of them
- further preprocessing operations that might be in the future needed depending on what is required in a particular Model_error.

The followed demo script demonstrates how such a library of different experiments/processes might look like. This is, of course, the first draft and can be further improved/developed.

`class Experiment:
    def __init__(self, date="01.01.2021"):
        self._date = date
    
class QuasiStaticTension(Experiment):
    def __init__(self, L=1.0, ts=[], us=[], fs=[], date="01.01.2021"):
        super().__init__(date)
        self.L = L
        self.ts = ts # time-steps
        self.us = us # the measured displacement at the tip
        self.fs = fs # the measured force at the tip
    
    def add_u(self, t, u, f):
        if len(self.ts)==0:
            last_t=-1
        else:
            last_t=self.ts[-1]
        assert (t>last_t and t>=0)
        self.ts.append(t)
        self.us.append(u)
        self.fs.append(f)
        

class QuasiStaticTension_Distributed(QuasiStaticTension):
    """
    The only difference with "QuasiStaticTension" is that here the displacements are measured distributedly over the specimen.
    At each time-step (self.ts), the positions over which the displacements are measured are listed in the corresponding entry of self.xs .
    So, every entry of self.us and self.xs are again an array.
    """
    def __init__(self, L=1.0, ts=[], xs=[], us=[], fs=[], date="01.01.2021"):
        super().__init__(L, ts, us, fs, date)
        self.xs = xs
        self.covs = []
        
    def add_u(self, t, xs, us, f):
        super().add_u(t, us, f)
        self.xs.append(xs)
        
    def set_spatial_correlation(self):
        for xs in self.xs:
            self.covs.append(spatial_correlation_1D(xs))


############ USEFUL STATIC METHODs (independent of experiment) ##############
            
def spatial_correlation_1D(xs, _method='exponential'):
    """
    returns the spetial correlation of the points "xs" in 1-D
    """
    cov = 1 ###### to be implemented ....
    return cov

def spatial_correlation_2D(xs, _method='exponential'):
    """
    returns the spetial correlation of the points "xs" in 2-D
    """
    cov = 1 ###### to be implemented ....
    return cov

### similar methods regarding correlation w.r.t. the time can be developed.`

**Comment by joergfunger** [comment]
1. The experiment class is somehow what we currently develop in the other projects based on an ontology, but I think we will end up reading in all the values from the database in a similar way as you describe, so this is what we will probably have to define. In the current implementation, this is essentially the yaml file with the data, but we could also have a class representation of it.
2. The Cov is in my opinion not an experimental property, but often defined by the one responsible for the calibration (even though there might be experimental evidence related to the magnitude itself). The challenge I see is actually not the definition of the Cov (there is an implementation of @TTitscher in https://github.com/BAMresearch/BayesianInference/pull/4), but rather the definition of how we apply this to our model error vector. I would rather not build a complete Cov of all subproblems, because this might end up in a huge matrix, but rather have subsets related to each individual experiment (assuming that the different experiments are independent, then the off-diagonal elements of the block-Cov are zero anyway), and also for each independent sensor system (so if as in our model bridge force and displacement sensors are independent, the corresponding model errors are independent and we could build a cov for each system separately). Or, in the case of no correlation or just pure optimization, each sensor class then gets another measurement accuracy/scaling factor to make different sensor types comparable. These parameters are then not model parameters, but rather hyper parameters (@TTitscher is currently adding these type of parameters as additional entries in the parameter lists). But this would mean to be able to access each individual set of model errors (e.g. model_error['my_first_experiment']['my_space_time_displacement_sensors']), thus instead of a single vector we would have to structure our residual vector. This would also allow us to store additional information there, e.g. at the very low level have a baseClass for space/time sensor arrays with time and location for each sensor.

**Comment by TTitscher** [comment]
Sorry for not really contributing here. That is mainly, because I am not really into that topic. For example, I always thought we need some kind of transformation matrix based on the eigenvalues of COV to project the correlated model error in some kind of "uncorrelated space". And, for my current problems with over thousand entries in the model error, this (dense) COV hardly fits in memory and the eigenvalue analysis just takes to long. 

Anyways, as always, I like to mention my two cents about those design issues. Including correlations in an inference problem is almost certainly defined mathematically. If not, that should be the first step. Implementing the correct math in different scenarios (correlation in [model, data, multiple models, space-time stuff, ...]) will quite naturally show common code and patterns that can be extracted to an interface.
