### ISSUE TITLE
open-bis integration

### ISSUE THREAD

**Issue by aradermacher** [BAMresearch/LebeDigital#56]
adding the possibility to upload the raw data with metadata in open-bis

**Comment by joergfunger** [comment]
A challenge to be discussed (maybe with Rukeia) is the integration into the CI, since I'm not sure how we could access (both reading and writing) from here in github to openBIS.

**Comment by joergfunger** [comment]
@cezary17 It might be an option to discuss some of the design questions already here in the issue before implementing everything which might allow getting a review sooner and avoid potential structural changes again.

**Comment by aradermacher** [comment]
Should we work with "metadata_yaml_templates" for the Emodul experiment as well as for the Mixtures for creating new openbis Objects?

Where the template.yaml inlcudes all possible metadata variables with name, data type and maybe description like

experiment_Emodul.yaml
- diameter:
   - descrpition: "diameter of sample"
   - data_type: FLOAT
- experimentName
   - description: "Name of experiment"
   - data_type: STRING 
....

**Comment by joergfunger** [comment]
I think the question here is if this file is stored in our git repo (defining the sructure), or if that is created on the fly (either by the user who creates a new experimental step template for openBIS) or by the user who wants to push/pull data from openBIS (by just quering that from openBIS). I'm still not fully sure what the best option is. The pro/con for having a data structure defined both in python and openBIS (vs only in openBIS)
Pro
1. we could work offline (without openBIS access) with the data structure (e.g. in a pydoit job first download the files, and then do something afterwards). Though this would probably be possible by downloading the metadata template (yaml) file as well.
2. When writing export functions (e.g. to the knowledge graph), this will IMO not be automatical using a flexible set of meta data, but rather fixed for a given set. If the meta data is changed, we would have to change the export. Thus, checking what we have already eported (based on the python templates) would be nice
Con
1. We would define the structure twice, thus it is not fully clear how we could handle new openBIS objects that are not created within our framework (because we would first have to create this template to work with it rather than creating that on the fly).

So IMO (but that is open for discussion) the template is nice to have, but maybe creating that on the fly (by having a routine in our openBIS interface that downloads/uploads those templates) would be sufficient. All the other advantages are related to the ttl export where we do not have a clear vision on how this would work at the end.
